title: "Jacob Sass"
email: sassj [at] mit.edu
description: >-
  Jacob Sass Personal Website
baseurl: ""
url: ""
theme: minima
plugins:
  - jekyll-feed
header_pages:
  - index.md
  - research.md
  - blog.md
  - contact.md
